require_relative '../../node_modules/@capacitor/ios/scripts/pods_helpers'

platform :ios, '13.0'
use_frameworks!

# workaround to avoid Xcode caching of Pods that requires
# Product -> Clean Build Folder after new Cordova plugins installed
# Requires CocoaPods 1.6 or newer
install! 'cocoapods', :disable_input_output_paths => true

def capacitor_pods
  pod 'Capacitor', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorCordova', :path => '../../node_modules/@capacitor/ios'
  pod 'CapacitorHaptics', :path => '../../node_modules/@capacitor/haptics'
  pod 'CapacitorStatusBar', :path => '../../node_modules/@capacitor/status-bar'
  pod 'RevenuecatPurchasesCapacitor', :path => '../../node_modules/@revenuecat/purchases-capacitor'
end

target 'App' do
  capacitor_pods
  # Add your Pods here
end

post_install do |installer|
  assertDeploymentTarget(installer)
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
    end
  end

  # Xcode 26 added StoreKit.SubscriptionPeriod which clashes with
  # RevenueCat.SubscriptionPeriod in PurchasesHybridCommon v7.x.
  # Qualify every unambiguous reference so the build succeeds.
  Dir.glob("#{installer.sandbox.root}/PurchasesHybridCommon/**/*.swift").each do |file|
    content = File.read(file)
    patched = content.gsub(/(?<![.\w:])SubscriptionPeriod/, 'RevenueCat.SubscriptionPeriod')
    File.write(file, patched) if content != patched
  end
end
